#!/bin/bash
echo "Entered file $0 ---------------------------------------------------"

# update autogenerated chosen
# sopc2dts does not support stdoutpath
sed -i -E "s/(bootargs.+)\".*\"(.+)/\1\"$BOOTARGS\"\2/" ${OUTPUT_DTS}
sed -i -E "/(\}\; \/\/end chosen)/i \	\	stdout-path = \"$STDOUTPATH\";" ${OUTPUT_DTS}

# copy template
cp ./input/overlaytemplate.dtso ${OUTPUT_DTSO}

chmod 777 ${OUTPUT_DTSO}


# get peripherals inside bridge
PERIPHERALS="$(perl -0777 -ne 'print $1 if /(?:hps_0_bridges:)(?:.+?ranges.+?;)(.*?)(?:}; \/\/end bridge)/sp' "${OUTPUT_DTS}")"
echo "$PERIPHERALS" > ".tmp"

# fix interrupt flag settings
# see platform_get_irq https://patchwork.kernel.org/patch/9264913/
perl -i -p -e 's/(interrupts.*<)(.*? .*? )(.*?)(>;)/$1$2\Q0\E$4$5/g' ".tmp"

# fill template with peripherals
perl -i -p -e '$text=`cat .tmp`; s/INSERTIONMARK/$text/g' ${OUTPUT_DTSO}

# strip bridge peripherals
sed -i -E "/hps_0_bridges/,/\(hps_0_bridges\)/d" ${OUTPUT_DTS}

echo "Leaving file $0 ---------------------------------------------------"
